---
- name: Create AWS ec2 instance
  hosts: local
  connection: local
  gather_facts: false
  vars:
    keypair             : my-ssh-frankfurt
    instance_type       : t2.micro
    image               : ami-03c3a7e4263fd998c
    region              : eu-central-1
    count               : 2
    security_group      : Ansible-SecurityGroup
    aws_access_key      : enter_your_key
    aws_secret_key      : enter_your_key


  tasks:
    - name: Create new sec group (22 and 80 port open)
      ec2_group:
        name            : "{{ security_group }}"
        description     : Sec group for servers with port 22,80,443
        region          : "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"

    - name: Create new AWS ES2 server
      ec2:
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        group: "{{ security_group }}"
        region: "{{ region }}"
        instance_tags: 
          Name: Testing server
          Type: ForMyTest
        count: "{{ count }}"
        wait: true
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2

    - name: Print EC2 var
      debug: var=ec2
































